### PR TITLE
lightline hl assign and bug fix

### LINKED ISSUE #57: bug: lightline colorscheme is not applied when set it up
### Did you check docs and existing issues?

- [X] I have read all the solarized-osaka.nvim docs
- [X] I have searched the existing issues of solarized-osaka.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.1

### Operating system/version

Windows 10 22H2

### Describe the bug

The Solarized osaka's lightline colorscheme is not applied when it's called using `let g:lightline = {'colorscheme' = 'solarized-osaka'}`.

### Steps To Reproduce

1. Open Neovim with `nvim -u repro.lua`
2. Type the command `:messages`
3. It should says: "lightline.vim: Could not load colorscheme solarized-osaka."

### Expected Behavior

The lightline colorscheme should be applied with no problems.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "craftzdog/solarized-osaka.nvim",
  "craftzdog/solarized-osaka.nvim",
  "itchyny/lightline.vim"
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.g.lightline = {colorscheme = 'solarized-osaka'}
vim.o.laststatus = 3
vim.cmd.colorscheme("solarized-osaka")
```

### PR DESCRIPTION
**Pull request by redoxahmii**
Fixes #57 
Files in `autoload` for `runtimepath` require the `.vim` files to be `snake_case` so changed it.
Also a lot of undefined colors so assigned them to be close to how `lualine` appears.

### CODE REVIEW

**Comment by redoxahmii** [comment]
I've also included it inside the README.md as it requires it to be used as `snake_case` instead of `kebab-case`.

This is how it looks now.
image

File: lua/solarized-osaka/groups/which-key.lua [hunk 1]
```diff
@@ -7,7 +7,6 @@ function M.get(c, opts)
     WhichKeyGroup     = { fg = c.blue },
     WhichKeyDesc      = { fg = c.magenta },
     WhichKeySeperator = { fg = c.base01 },
-    WhichKeySeparator = { fg = c.base01 },
```
Comment (killitar) [inline lua/solarized-osaka/groups/which-key.lua:10]: You deleted the wrong line. The plugin doesn't have a group called WhichKeySeperator. You need to delete line 9.

Comment (redoxahmii) [reply lua/solarized-osaka/groups/which-key.lua:10]: Could you recheck cause it seems to be included at the end of [which-key.nvim](https://github.com/folke/which-key.nvim) ?

Comment (redoxahmii) [reply lua/solarized-osaka/groups/which-key.lua:10]: I've added it back as it is clearly stated in `which-key.nvim` README file.
image

Thankfully I checked it.

Comment (killitar) [reply lua/solarized-osaka/groups/which-key.lua:10]: WhichKeySeparator group exists leave this group, delete only _WhichKeySeperator_

**Comment by redoxahmii** [comment]
After checking on a few other plugins the conclusion is that most people are setting this up during setup function for the theme so I've removed the README.md part and instead added it inside the initial setup of the colorscheme.
This way the users don't have to set it up manually and should only apply when using with this colorscheme.
